### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by joshuawarner32** [bigfatbrowncat/avian-pack#2]
I'm tried to get avian-pack compiling on macosx and ios, but I ran into several issues:
- The avian version should be updated with the upstream (https://github.com/ReadyTalk/avian), where several compatibility issues have been fixed with newer compilers
- Building the luni classes fails when using Java 8.  The following patch to android/libcore fixes it.  I wonder if this has perhaps been fixed upstream.

```
diff --git a/luni/src/main/java/java/util/EnumMap.java b/luni/src/main/java/java/util/EnumMap.java
index dfacb46..a787dda 100644
--- a/luni/src/main/java/java/util/EnumMap.java
+++ b/luni/src/main/java/java/util/EnumMap.java
@@ -159,7 +159,7 @@ public class EnumMap<K extends Enum<K>, V> extends AbstractMap<K, V> implements
                 throw new NoSuchElementException();
             }
             prePosition = position++;
-            return type.get(new MapEntry(enumMap.keys[prePosition],
+            return (E)type.get(new MapEntry(enumMap.keys[prePosition],
                     enumMap.values[prePosition]));
         }
```
- Lastly, when using `make platform=ios bootimage=true` in the root of avian-pack, I get the following error, which I have yet to find a solution to:

```
linking build/ios-x86_64-bootimage-android/avian
Undefined symbols for architecture x86_64:
  "_opendir$INODE64", referenced from:
      searchForTZFile(char const*, DefaultTZInfo*) in libicuuc.a(putil.ao)
      _OPENSSL_DIR_read in libcrypto.a(o_dir.o)
  "_readdir$INODE64", referenced from:
      searchForTZFile(char const*, DefaultTZInfo*) in libicuuc.a(putil.ao)
      _OPENSSL_DIR_read in libcrypto.a(o_dir.o)
ld: symbol(s) not found for architecture x86_64
```

@bigfatbrowncat - any ideas?  Have you seen this last problem before?

**Comment by bigfatbrowncat** [comment]
I'll take a look at this, thanks. I've never tried Java 8 yet, but if such an easy patch fixes build on it, I'll accept it of course.

About the second part - the only thing that I know so far is that `libicuuc.a` is a part of ICU4C library. I don't have an idea why it doesn't compile for iOS, maybe we should update the version upstream...

**Comment by bigfatbrowncat** [comment]
Hi! I've found some solution concerning missing symbols on iOS.

I've found it out there in the web. Looks like  Please take a look:

```
#include <dirent.h>
#include <fnmatch.h>

extern "C" DIR * opendir$INODE64( char * dirName );
DIR * opendir$INODE64( char * dirName )
{
    return opendir( dirName );
}

extern "C" struct dirent * readdir$INODE64( DIR * dir );
struct dirent * readdir$INODE64( DIR * dir )
{
    return readdir( dir );
}
```

It looks like these functions should be included into `classpath-android.cpp` file with check for the platform.

@joshuawarner32, could you try to check this (I'm not familiar with iOS)? I'll be thankful for a patch.

**Comment by joshuawarner32** [comment]
@bigfatbrowncat - I played with defining those in various different ways, to no avail.  It looks like the leading advice on the interwebs (https://github.com/krzyzanowskim/OpenSSL/issues/7) is to update openssl, which we may or may not actually have control over.

**Comment by bigfatbrowncat** [comment]
Ok, I'll update OpenSSL. I hope that will help

**Comment by bigfatbrowncat** [comment]
I've updated OpenSSL to 1.0.1j (used in the latest Android 5.1.1). In addition I've updated Avian to the current upstream version.
@joshuawarner32, please test your iOS problem again and if the build succeeds, let me know how to make it correctly. I'll add the proper command to the main makefile.

Although my main target was desktop systems, easy iOS support would be a good bonus.

**Comment by nadavwr** [comment]
@bigfatbrowncat I'm looking into using avian on iOS, and the extended library coverage of avian-pack is appealing. What's the current state of avian-pack on iOS?
