### ISSUE TITLE
API Sheet

### ISSUE THREAD

**Issue by iskl** [bigfatbrowncat/avian-pack#3]
Thanks for your great job.

I am wondering whether there is a sheet indicating the available APIs included when I use the "avian" file in avian-pack pre-build package? I tried the pre-build "avian" and found that core API of JDK is inclusive and swing is exclusive.

**Comment by bigfatbrowncat** [comment]
Actually, only Java Core classes are supported out-of-the-box.
Some other classes are provided cause they are a part of Android classpath too.

**Comment by iskl** [comment]
I see. Thanks.
